apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "aurora-k8s-agent.labels" . | nindent 4 }}
data:
  policy.json: |
    {{ dict "version" 1 "users" .Values.policy.users | toJson | nindent 4 }}
