{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "aurora-k8s-agent.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "aurora-k8s-agent.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
    {{- if .Values.api.enabled }}
    - ports:
        - protocol: TCP
          port: {{ .Values.api.port }}
      {{- with .Values.networkPolicy.apiAllowFrom }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
        - protocol: TCP
          port: 443
{{- end }}
