{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "aurora-k8s-agent.labels" . | nindent 4 }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      {{- include "aurora-k8s-agent.selectorLabels" . | nindent 6 }}
{{- end }}
